site_name: SafetyFolder Documentation
theme:
  name: material
  features:
    - content.action.edit
    - navigation.expand
    - navigation.top
    - navigation.instant


  nav:
  - 'index.md'
  - 'userguide.md'