site_name: SafetyFolder Documentation
theme:
  name: material
  features:
    - content.action.edit
    - navigation.path
    - toc.follow
    - toc.integrate
 markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences